/**
 * Helper functions for pr_fixer capability.
 * Parses review comments and generates todo specs from review issues.
 */

import type { ReviewIssueData } from '../pr-reviewer/pr-reviewer.schema.js'

/**
 * Extract ReviewIssueData[] from a pr_reviewer comment body.
 * Parses the "### Issues Data" JSON code block.
 */
export function parseReviewIssuesFromComment(commentBody: string): ReviewIssueData[] {
  const match = commentBody.match(/### Issues Data\n\n```json\n([\s\S]*?)\n```/)
  if (!match?.[1]) return []

  try {
    const parsed: unknown = JSON.parse(match[1])
    if (!Array.isArray(parsed)) return []
    return parsed as ReviewIssueData[]
  } catch {
    return []
  }
}

/**
 * Filter to only manual (non-auto-fixable) issues.
 * @deprecated Use filterUnfixedIssues instead — reviewer now always attempts auto-fixes.
 */
export function filterManualIssues(issues: ReviewIssueData[]): ReviewIssueData[] {
  return issues.filter((issue) => !issue.autoFixable)
}

/**
 * Filter to all unfixed issues (excluding LOW severity).
 * Since the reviewer now always runs in review-fix mode and attempts auto-fixes,
 * any issue remaining in the PR comment is unfixed regardless of its original classification.
 */
export function filterUnfixedIssues(issues: ReviewIssueData[]): ReviewIssueData[] {
  return issues.filter((issue) => issue.severity !== 'LOW')
}

/**
 * Determine if an issue requires the full spec pipeline (complex) vs direct inline fix (simple).
 * Complex issues: architecture/design, multi-file refactors, new feature requirements.
 * Simple issues: everything else (code fixes, error handling, type changes).
 */
export function isComplexIssue(issue: ReviewIssueData): boolean {
  const complexCategories = ['architecture']
  const complexKeywords = [
    'redesign',
    'refactor architecture',
    'restructure',
    'new module',
    'new service',
    'design pattern',
    'dependency injection',
    'circular dependency',
  ]

  if (complexCategories.includes(issue.category)) return true

  const lowerTitle = issue.title.toLowerCase()
  const lowerDesc = issue.description.toLowerCase()
  return complexKeywords.some((kw) => lowerTitle.includes(kw) || lowerDesc.includes(kw))
}

/**
 * Generate a spec file path for PR review fixes.
 */
export function buildSpecPath(project: string, prNumber: number): string {
  const date = new Date().toISOString().slice(0, 10)
  return `docs/specs/${project}/todo/${date}-pr-${prNumber}-review-fixes.md`
}

/**
 * Generate todo spec markdown content from review issues.
 */
export function generateSpecContent(
  prNumber: number,
  issues: ReviewIssueData[],
  project: string,
): string {
  const date = new Date().toISOString().slice(0, 10)
  const affectedFiles = [...new Set(issues.map((i) => i.file))]

  const lines: string[] = [
    `**App**: ${project}`,
    `**Status**: DRAFT`,
    `**Created**: ${date}`,
    '',
    `# Fix PR #${prNumber} review findings`,
    '',
    '## Context',
    '',
    `The pr_reviewer tool identified ${issues.length} manual issue(s) in PR #${prNumber} that require code changes.`,
    'This spec was auto-generated by pr_fixer to address these findings.',
    '',
    '## Affected Files',
    '',
    ...affectedFiles.map((f) => `- \`${f}\``),
    '',
    '## Implementation Steps',
    '',
  ]

  for (let i = 0; i < issues.length; i++) {
    const issue = issues[i]!
    const lineRef = issue.line ? `:${issue.line}` : ''

    lines.push(
      `### Step ${i + 1}: [${issue.severity}] ${issue.title}`,
      '',
      `**File:** \`${issue.file}${lineRef}\``,
      `**Category:** ${issue.category || 'general'}`,
      '',
      issue.description,
      '',
    )

    if (issue.suggestedFix) {
      lines.push(`**Suggested Fix:** ${issue.suggestedFix}`, '')
    }

    lines.push(
      '**Acceptance Criteria:**',
      `- [ ] ${issue.title} is resolved`,
      `- [ ] No regression in existing tests`,
      '',
    )
  }

  lines.push('## TDD Test Cases', '', '### Verification Tests', '')

  for (const issue of issues) {
    lines.push(`- Verify ${issue.title.toLowerCase()} is fixed`)
  }

  lines.push(
    '- All existing tests continue to pass',
    '',
    '## Verification',
    '',
    '1. `npm run build` — must succeed',
    '2. `npm test` — all tests must pass',
    '',
    '## For Implementation',
    '',
    '| Field | Value |',
    '|-------|-------|',
    `| **Project** | \`packages/${project}\` |`,
    `| **Test** | \`npm test\` |`,
    `| **Build** | \`npm run build\` |`,
  )

  return lines.join('\n')
}
